version: '2.4'

services:
  monster-relodex:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    # depends_on:
    #   - backend
    volumes:
      - /app/node_modules
      - ./:/app/:delegated
    # environment:
    #   database__client: mysql
    #   database__connection__host: db
    #   database__connection__user: root
    #   database__connection__password: YOURDBPASSWORDhere
    #   database__connection__database: ghost

  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - 3100:3100
  #   # depends_on:
  #   #   - db
  #   volumes:
  #     - /app/node_modules
  #     - ./backend:/app/:delegated
#   db:
#     image: mysql:5
#     volumes:
#       #GOOD: created a named volume so our data is kept between docker-compose ups
#       - db:/var/lib/mysql
#     environment:
#       MYSQL_ROOT_PASSWORD: YOURDBPASSWORDhere

# volumes:
#   db:
